#definiation de l'image docker utilise

image: php:7.4.23-cli

#executer avant chaque script
before_script:
  - ls

#script nome 'test' excuatnt un fichier php
newtest:
  script:
    - cd Classes
    - cd System
    - php Main.php